# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'LZEasemob3' do

pod "MJExtension"
pod "Masonry"
pod 'FMDB'
pod "MJRefresh"
pod "AFNetworking", '3.2.1'
pod "ReactiveCocoa", "~> 2.5"
pod 'Hyphenate_CN', '~> 3.2.2.2'
pod 'UMengAnalytics'
pod 'YTKKeyValueStore'

end

target 'LZEasemob3Tests' do

end

target 'LZEasemob3UITests' do

end

